# Generated by Django 4.2.15 on 2025-10-14 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_merge_20250920_0032'),
        ('content', '0006_remove_lesson_slug_global_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0004_flashcard_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Chapter Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_chapters', to='courses.course', verbose_name='Course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_flashcard_chapters', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Flashcard Chapter',
                'verbose_name_plural': 'Flashcard Chapters',
                'ordering': ['course', 'order', 'title'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='QuestionBankChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Chapter Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_chapters', to='courses.course', verbose_name='Course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_question_bank_chapters', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Question Bank Chapter',
                'verbose_name_plural': 'Question Bank Chapters',
                'ordering': ['course', 'order', 'title'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course this flashcard belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='courses.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course this question belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Legacy field - kept for backward compatibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_flashcards', to='content.lesson', verbose_name='Lesson (Legacy)'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Legacy field - kept for backward compatibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_questions', to='content.lesson', verbose_name='Lesson (Legacy)'),
        ),
        migrations.CreateModel(
            name='QuestionBankTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Topic Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='assessment.questionbankchapter', verbose_name='Chapter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_question_bank_topics', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Question Bank Topic',
                'verbose_name_plural': 'Question Bank Topics',
                'ordering': ['chapter', 'order', 'title'],
                'unique_together': {('chapter', 'order')},
            },
        ),
        migrations.CreateModel(
            name='FlashcardTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Topic Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='assessment.flashcardchapter', verbose_name='Chapter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_flashcard_topics', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Flashcard Topic',
                'verbose_name_plural': 'Flashcard Topics',
                'ordering': ['chapter', 'order', 'title'],
                'unique_together': {('chapter', 'order')},
            },
        ),
        migrations.AddField(
            model_name='flashcard',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='The topic this flashcard belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='assessment.flashcardtopic', verbose_name='Topic'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='The topic this question belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.questionbanktopic', verbose_name='Topic'),
        ),
    ]
