# Generated by Django 4.2.15 on 2025-10-14 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_flashcardchapter_questionbankchapter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='lesson',
        ),
    ]
