# Generated by Django 4.2.15 on 2025-10-14 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_merge_20250920_0032'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0006_remove_flashcard_lesson_remove_questionbank_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('is_free', models.BooleanField(default=False, verbose_name='Is Free')),
                ('image', models.ImageField(blank=True, null=True, upload_to='flashcard_products/', verbose_name='Product Image')),
                ('tags', models.JSONField(blank=True, default=list, help_text='JSON array of tags for categorization', verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_products', to='courses.course', verbose_name='Course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_flashcard_products', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Flashcard Product',
                'verbose_name_plural': 'Flashcard Products',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='QuestionBankProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
                ('is_free', models.BooleanField(default=False, verbose_name='Is Free')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_bank_products/', verbose_name='Product Image')),
                ('tags', models.JSONField(blank=True, default=list, help_text='JSON array of tags for categorization', verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_products', to='courses.course', verbose_name='Course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_question_bank_products', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Question Bank Product',
                'verbose_name_plural': 'Question Bank Products',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'created_by')},
            },
        ),
        migrations.AlterModelOptions(
            name='flashcardchapter',
            options={'ordering': ['product', 'order', 'title'], 'verbose_name': 'Flashcard Chapter', 'verbose_name_plural': 'Flashcard Chapters'},
        ),
        migrations.AlterModelOptions(
            name='questionbankchapter',
            options={'ordering': ['product', 'order', 'title'], 'verbose_name': 'Question Bank Chapter', 'verbose_name_plural': 'Question Bank Chapters'},
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='course',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='flashcardchapter',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='questionbankchapter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The product this flashcard belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='assessment.flashcardproduct', verbose_name='Flashcard Product'),
        ),
        migrations.AddField(
            model_name='flashcardchapter',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='assessment.flashcardproduct', verbose_name='Flashcard Product'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The product this question belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.questionbankproduct', verbose_name='Question Bank Product'),
        ),
        migrations.AddField(
            model_name='questionbankchapter',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='assessment.questionbankproduct', verbose_name='Question Bank Product'),
        ),
        migrations.AlterUniqueTogether(
            name='flashcardchapter',
            unique_together={('product', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='questionbankchapter',
            unique_together={('product', 'order')},
        ),
        migrations.CreateModel(
            name='QuestionBankProductEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='assessment.questionbankproduct', verbose_name='Question Bank Product')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Question Bank Product Enrollment',
                'verbose_name_plural': 'Question Bank Product Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'product')},
            },
        ),
        migrations.CreateModel(
            name='FlashcardProductEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='assessment.flashcardproduct', verbose_name='Flashcard Product')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Flashcard Product Enrollment',
                'verbose_name_plural': 'Flashcard Product Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'product')},
            },
        ),
        migrations.RemoveField(
            model_name='flashcardchapter',
            name='course',
        ),
        migrations.RemoveField(
            model_name='questionbankchapter',
            name='course',
        ),
    ]
