# Generated by Django 4.2.15 on 2025-10-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_flashcardproduct_questionbankproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardproductenrollment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='flashcardproductenrollment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='flashcardproductenrollment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('free', 'Free')], default='free', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='flashcardproductenrollment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Reference'),
        ),
        migrations.AddField(
            model_name='flashcardproductenrollment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='flashcardproductenrollment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID'),
        ),
        migrations.AddField(
            model_name='questionbankproductenrollment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='questionbankproductenrollment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='questionbankproductenrollment',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('free', 'Free')], default='free', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='questionbankproductenrollment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Reference'),
        ),
        migrations.AddField(
            model_name='questionbankproductenrollment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='questionbankproductenrollment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID'),
        ),
    ]
