# Generated by Django 4.2.15 on 2025-10-21 04:05

from django.db import migrations, models
import django.core.validators
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0008_flashcardproductenrollment_amount_paid_and_more"),
    ]

    operations = [
        # Add new fields to QuestionBankProductEnrollment
        migrations.AddField(
            model_name='questionbankproductenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='questionbankproductenrollment',
            name='enrollment_date',
            field=models.DateTimeField(default=timezone.now, verbose_name='Enrollment Date'),
        ),
        migrations.AddField(
            model_name='questionbankproductenrollment',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AddField(
            model_name='questionbankproductenrollment',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Accessed'),
        ),
        migrations.AddField(
            model_name='questionbankproductenrollment',
            name='progress',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress %'),
        ),
        migrations.AddField(
            model_name='questionbankproductenrollment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AddField(
            model_name='questionbankproductenrollment',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Payment Amount'),
        ),
        
        # Add new fields to FlashcardProductEnrollment
        migrations.AddField(
            model_name='flashcardproductenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='flashcardproductenrollment',
            name='enrollment_date',
            field=models.DateTimeField(default=timezone.now, verbose_name='Enrollment Date'),
        ),
        migrations.AddField(
            model_name='flashcardproductenrollment',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AddField(
            model_name='flashcardproductenrollment',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Accessed'),
        ),
        migrations.AddField(
            model_name='flashcardproductenrollment',
            name='progress',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress %'),
        ),
        migrations.AddField(
            model_name='flashcardproductenrollment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AddField(
            model_name='flashcardproductenrollment',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Payment Amount'),
        ),
        
        # Remove old fields from QuestionBankProductEnrollment
        migrations.RemoveField(
            model_name='questionbankproductenrollment',
            name='enrolled_at',
        ),
        migrations.RemoveField(
            model_name='questionbankproductenrollment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='questionbankproductenrollment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='questionbankproductenrollment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='questionbankproductenrollment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='questionbankproductenrollment',
            name='payment_reference',
        ),
        
        # Remove old fields from FlashcardProductEnrollment
        migrations.RemoveField(
            model_name='flashcardproductenrollment',
            name='enrolled_at',
        ),
        migrations.RemoveField(
            model_name='flashcardproductenrollment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='flashcardproductenrollment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='flashcardproductenrollment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='flashcardproductenrollment',
            name='payment_reference',
        ),
    ]
