# Generated by Django 4.2.15 on 2025-10-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0009_auto_20251021_0405"),
    ]

    operations = [
        # First, we need to handle the enrollment_date field properly
        # Since SQLite doesn't support altering column constraints directly,
        # we'll need to recreate the table or use a different approach
        
        # For now, let's just update the model options and remove the amount_paid field
        migrations.AlterModelOptions(
            name="flashcardproductenrollment",
            options={
                "ordering": ["-enrollment_date"],
                "verbose_name": "Flashcard Product Enrollment",
                "verbose_name_plural": "Flashcard Product Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="questionbankproductenrollment",
            options={
                "ordering": ["-enrollment_date"],
                "verbose_name": "Question Bank Product Enrollment",
                "verbose_name_plural": "Question Bank Product Enrollments",
            },
        ),
        migrations.RemoveField(
            model_name="flashcardproductenrollment",
            name="amount_paid",
        ),
        
        # Note: The enrollment_date field already exists in the database
        # The auto_now_add=True behavior will be handled by Django at the application level
        # We don't need to alter the field in the database since SQLite doesn't support
        # changing column constraints directly
    ]
