# Generated by Django 4.2.15 on 2025-10-21 07:00

from django.db import migrations, models
from django.utils import timezone


def set_default_enrollment_dates(apps, schema_editor):
    """Set default enrollment dates for existing records"""
    FlashcardProductEnrollment = apps.get_model('assessment', 'FlashcardProductEnrollment')
    QuestionBankProductEnrollment = apps.get_model('assessment', 'QuestionBankProductEnrollment')
    
    # Set default enrollment dates for existing FlashcardProductEnrollment records
    for enrollment in FlashcardProductEnrollment.objects.filter(enrollment_date__isnull=True):
        enrollment.enrollment_date = timezone.now()
        enrollment.save()
    
    # Set default enrollment dates for existing QuestionBankProductEnrollment records
    for enrollment in QuestionBankProductEnrollment.objects.filter(enrollment_date__isnull=True):
        enrollment.enrollment_date = timezone.now()
        enrollment.save()


def reverse_set_default_enrollment_dates(apps, schema_editor):
    """Reverse migration - no need to do anything"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0010_fix_enrollment_date_auto_now_add"),
    ]

    operations = [
        # First, make the field nullable temporarily
        migrations.AlterField(
            model_name="flashcardproductenrollment",
            name="enrollment_date",
            field=models.DateTimeField(null=True, blank=True, verbose_name="Enrollment Date"),
        ),
        migrations.AlterField(
            model_name="questionbankproductenrollment",
            name="enrollment_date",
            field=models.DateTimeField(null=True, blank=True, verbose_name="Enrollment Date"),
        ),
        
        # Set default values for existing records
        migrations.RunPython(
            set_default_enrollment_dates,
            reverse_set_default_enrollment_dates,
        ),
        
        # Now make the field non-nullable with default
        migrations.AlterField(
            model_name="flashcardproductenrollment",
            name="enrollment_date",
            field=models.DateTimeField(default=timezone.now, verbose_name="Enrollment Date"),
        ),
        migrations.AlterField(
            model_name="questionbankproductenrollment",
            name="enrollment_date",
            field=models.DateTimeField(default=timezone.now, verbose_name="Enrollment Date"),
        ),
    ]
