# Generated by Django 4.2.15 on 2025-10-28 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0009_merge_20250920_0032"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "daily_hours",
                    models.PositiveIntegerField(
                        choices=[(4, "4 hours"), (6, "6 hours"), (8, "8 hours")],
                        default=4,
                        verbose_name="Daily Study Hours",
                    ),
                ),
                (
                    "days_off",
                    models.JSONField(
                        default=list,
                        help_text='List of day names (e.g., ["Friday", "Saturday"])',
                        verbose_name="Days Off",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_schedules",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Study Schedule",
                "verbose_name_plural": "Study Schedules",
                "ordering": ["-created_at"],
                "unique_together": {("student", "course", "is_active")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="Hours"
                    ),
                ),
                (
                    "module_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Module ID"
                    ),
                ),
                (
                    "module_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Module Title"
                    ),
                ),
                (
                    "lesson_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Lesson ID"
                    ),
                ),
                (
                    "lesson_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Lesson Title"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Is Completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="courses.studyschedule",
                        verbose_name="Schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Item",
                "verbose_name_plural": "Schedule Items",
                "ordering": ["schedule", "date", "start_time", "order"],
                "indexes": [
                    models.Index(
                        fields=["schedule", "date"],
                        name="courses_sch_schedul_1e9936_idx",
                    ),
                    models.Index(
                        fields=["date", "is_completed"],
                        name="courses_sch_date_a26499_idx",
                    ),
                ],
            },
        ),
    ]
