# Generated by Django 4.2.15 on 2025-10-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_studyschedule_scheduleitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studyschedule",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="studyschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("student", "course"),
                name="unique_active_schedule_per_course",
            ),
        ),
    ]
