# Generated by Django 4.2.15 on 2025-10-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_alter_studyschedule_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="studyschedule",
            name="unique_active_schedule_per_course",
        ),
        migrations.AddConstraint(
            model_name="studyschedule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("student", "course", "is_active"),
                name="unique_active_schedule_per_student_course",
            ),
        ),
    ]
