# Generated by Django 4.2.15 on 2025-10-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_banner_background_color_banner_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Us', max_length=200, verbose_name='Title (EN)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('title_ar', models.CharField(default='اتصل بنا', max_length=200, verbose_name='العنوان (AR)')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='الوصف (AR)')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان (EN)')),
                ('address_ar', models.TextField(blank=True, null=True, verbose_name='العنوان (AR)')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='فيسبوك')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='تويتر')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='انستجرام')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لينكد إن')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='يوتيوب')),
                ('working_hours', models.TextField(blank=True, null=True, verbose_name='ساعات العمل (EN)')),
                ('working_hours_ar', models.TextField(blank=True, null=True, verbose_name='ساعات العمل (AR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'معلومات التواصل',
                'verbose_name_plural': 'معلومات التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=200, verbose_name='Title (EN)')),
                ('content', models.TextField(verbose_name='Content (EN)')),
                ('title_ar', models.CharField(default='سياسة الخصوصية', max_length=200, verbose_name='العنوان (AR)')),
                ('content_ar', models.TextField(blank=True, null=True, verbose_name='المحتوى (AR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سياسة الخصوصية',
                'verbose_name_plural': 'سياسات الخصوصية',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='RefundingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question (EN)')),
                ('answer', models.TextField(verbose_name='Answer (EN)')),
                ('question_ar', models.CharField(blank=True, max_length=300, null=True, verbose_name='السؤال (AR)')),
                ('answer_ar', models.TextField(blank=True, null=True, verbose_name='الإجابة (AR)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سؤال الاسترجاع',
                'verbose_name_plural': 'أسئلة الاسترجاع الشائعة',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms and Conditions', max_length=200, verbose_name='Title (EN)')),
                ('content', models.TextField(verbose_name='Content (EN)')),
                ('title_ar', models.CharField(default='الشروط والأحكام', max_length=200, verbose_name='العنوان (AR)')),
                ('content_ar', models.TextField(blank=True, null=True, verbose_name='المحتوى (AR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'الشروط والأحكام',
                'verbose_name_plural': 'الشروط والأحكام',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نص الزر (AR)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف (AR)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان (AR)'),
        ),
        migrations.AddField(
            model_name='coursecollection',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف (AR)'),
        ),
        migrations.AddField(
            model_name='coursecollection',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الاسم (AR)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نص الزر (EN)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title (EN)'),
        ),
        migrations.AlterField(
            model_name='coursecollection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='coursecollection',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name (EN)'),
        ),
    ]
