# Generated by Django 4.2.15 on 2025-10-11 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_contactinfo_privacypolicy_refundingfaq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Partner Name (EN)')),
                ('name_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الشريك (AR)')),
                ('logo', models.ImageField(upload_to='partnerships/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='شعار الشريك')),
                ('website', models.URLField(blank=True, max_length=500, null=True, verbose_name='موقع الشريك')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شريك',
                'verbose_name_plural': 'الشركاء',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
