# Generated by Django 4.1.7 on 2025-10-19 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان (AR)')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='الوصف (AR)')),
                ('image_1', models.ImageField(upload_to='card_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='الصورة الأولى')),
                ('image_2', models.ImageField(upload_to='card_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='الصورة الثانية')),
                ('image_3', models.ImageField(upload_to='card_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='الصورة الثالثة')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صورة كارد',
                'verbose_name_plural': 'صور الكارد',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('main', 'Main Banner'), ('header', 'Header Banner'), ('sidebar', 'Sidebar Banner'), ('about_us', 'About Us Banner'), ('why_choose_us', 'Why Choose Us Banner')], default='main', max_length=20, verbose_name='نوع البانر'),
        ),
    ]
