# Generated by Django 4.2.15 on 2025-10-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_instructor_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="اسم المدرب - يمكن إدخاله مباشرة أو ربطه بملف شخصي",
                max_length=2000,
                null=True,
            ),
        ),
    ]
