# Generated by Django 4.2.15 on 2025-10-24 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0007_instructor_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountFreeze",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_frozen",
                    models.BooleanField(default=False, verbose_name="الحساب مجمد"),
                ),
                (
                    "freeze_reason",
                    models.TextField(blank=True, null=True, verbose_name="سبب التجميد"),
                ),
                (
                    "freeze_start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ بداية التجميد"
                    ),
                ),
                (
                    "freeze_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ انتهاء التجميد"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "frozen_by_admin",
                    models.BooleanField(
                        default=False, verbose_name="تم التجميد من قبل الإدارة"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="ملاحظات الإدارة"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_freeze",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تجميد الحساب",
                "verbose_name_plural": "تجميد الحسابات",
                "ordering": ["-created_at"],
            },
        ),
    ]
