# Generated by Django 4.2.15 on 2025-10-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_accountfreeze"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountfreeze",
            name="has_used_freeze",
            field=models.BooleanField(
                default=False, verbose_name="تم استخدام التجميد من قبل"
            ),
        ),
    ]
